package com.spirittesting.db.frontend;

public enum ColumnAction {

    KEEP,
    GENERALIZE,
    DELETE,
    PERMUTATE,
    GENERATE_FIRSTNAME,
    GENERATE_LASTNAME,
    GENERATE_EMAIL,
    GENERATE_PHONE,
    GENERATE_STREET,
    GENERATE_CITY,
    GENERATE_ZIP,
    GENERATE_COUNTRY,
    GENERATE_DATE,
    GENERATE_TIME,
    GENERATE_DATETIME,
    GENERATE_INTEGER,
    GENERATE_FLOAT

}
